// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("F2F.Testing.NUnit.EF")]
[assembly: AssemblyProductAttribute("F2F.Testing")]
[assembly: AssemblyDescriptionAttribute("Unit and integration testing framework")]
[assembly: AssemblyVersionAttribute("1.4.2.0")]
[assembly: AssemblyFileVersionAttribute("1.4.2.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.4.2.0";
        internal const string InformationalVersion = "1.4.2.0";
    }
}
