// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("F2F.Testing.MSTest.Npgsql")]
[assembly: AssemblyProductAttribute("F2F.Testing")]
[assembly: AssemblyDescriptionAttribute("Unit and integration testing framework")]
[assembly: AssemblyVersionAttribute("2.0.0.0")]
[assembly: AssemblyFileVersionAttribute("2.0.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.0.0";
        internal const string InformationalVersion = "2.0.0.0";
    }
}
