// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("F2F.Testing.Xunit.EF")]
[assembly: AssemblyProductAttribute("F2F.Testing")]
[assembly: AssemblyDescriptionAttribute("Unit and integration testing framework")]
[assembly: AssemblyVersionAttribute("1.3.1.0")]
[assembly: AssemblyFileVersionAttribute("1.3.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.3.1.0";
    }
}
